### ISSUE TITLE
Minimum Request Level?

### ISSUE THREAD

**Issue by benyanke** [freshbitsweb/slack-error-notifier#1]
Hi,

Is there an option, or would you accept a PR for one, specifying the minimum request level? 

For example, in prod, I don't want to see debug, info, etc...only error and higher, even though I might want those info messages still in my log file.

**Comment by gauravmak** [comment]
I agree and would happily accept a PR for the same.

**Comment by gauravmak** [comment]
Option added with the new release. Thanks.
