### ISSUE TITLE
Call to undefined method Monolog\Logger::getMonolog()

### ISSUE THREAD

**Issue by diazsasak** [freshbitsweb/slack-error-notifier#10]
In Logger.php line 273:

  Call to undefined method Monolog\Logger::getMonolog()

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Logger::getMonolog() does not exist. you may try Logger::getLogger() ?

**Comment by gauravmak** [comment]
@diazsasak Which version of Laravel are you using?

**Comment by diazsasak** [comment]
@gauravmak laravel 5.7

**Comment by gauravmak** [comment]
@diazsasak This package is only for Laravel 5.5

From Laravel 5.6 onwards, you can send Slack messages for log messages without any package.

Check this - https://laravel.com/docs/5.7/logging

Thanks.
