### ISSUE TITLE
Call to undefined method Monolog\Logger::getMonolog()

### ISSUE THREAD

**Issue by fahadkhan1740** [freshbitsweb/slack-error-notifier#7]
The following error is showing up while installing using composer.
```
In Logger.php line 273:

Call to undefined method Monolog\Logger::getMonolog()
```

**Comment by gauravmak** [comment]
I just tried it in a fresh Laravel 5.5 installation and it works. Which version of Laravel did you try with?

**Comment by fahadkhan1740** [comment]
I did it with 5.7. It works great with 5.5

**Comment by gauravmak** [comment]
This package is for Laravel 5.5 only. As per the note in the Readme, [Laravel Log Enhancer](https://github.com/freshbitsweb/laravel-log-enhancer) package can be used for Laravel 5.6+.

Thanks.
